name             'jsontest'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures a file, based on a template that has all ip addresses'
long_description 'Long description'
version          '0.1.0'